### PR TITLE
Several bug fixes

### PR DESCRIPTION
**Pull request by sjvc**
Commit 1e3958b
Some assignments were wrong, I fixed them.

Commit 7a6a806
In Spanish "espalda" means "back", but as a body part (I'm native Spanish speaker)

Commit 56ea4c0
Back button behavior now works this way:
- If "Adjust back behavior" is unchecked: pressing back key brings the user back to alarm panel (as it was working before adding HassWebView).
- If "Adjust back behavior" is checked: pressing back key closes dialogs, and brings the user back to "Overview" section if any other is selected. It not behaves exactly like the browser back button (browser back button also navigates through previous visited tabs, but I don't like it because it doesn't feel like a native Android app, it's not useful, and makes going back to alarm panel slower).

Also, when the user goes back from Home Assistant view to Alarm Panel view (either by touching bottom bar button, or pressing back button), if there is a dialog visible, then it will be closed to re-enable paging (remember that it's disabled when a dialog is shown in order to get sliders working).

If you find any bug, please tell me and I'll fix it.

Thanks!

### CODE REVIEW

**Comment by thanksmister** [comment]
Looks like we are missing this method now? webView.closeMoreInfoDialog()

**Comment by sjvc** [comment]
In Android Studio select Tools -> Android -> Sync Project with Gradle Files

Please let me know if it's working now.

2018-03-13 19:45 GMT+01:00 Michael Ritchie <notifications@github.com>:

**Comment by thanksmister** [comment]
Liso.. gracias!

**Comment by sjvc** [comment]
¡Gracias a ti! :D

2018-03-13 19:48 GMT+01:00 Michael Ritchie <notifications@github.com>:

**Comment by thanksmister** [comment]
I started a rollout of v0.7.4 to 25% of installed users (160 or so).  We'll see if we have any issues and then I can update the app as needed.

**Comment by sjvc** [comment]
Perfect. Let me know if any bug is found.

2018-03-13 20:01 GMT+01:00 Michael Ritchie <notifications@github.com>:

**Pull request merged**
